version: '3.1'
services:

  # Application container
  dotnet:
    build: .
    image: kri5t-paymentgateway:latest
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "aJyS68KNZP9"
      ACCEPT_EULA: "Y"
            