// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentGatewayDatabase;

namespace PaymentGatewayDatabase.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190716205157_IntitialPaymentSchema")]
    partial class IntitialPaymentSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentGatewayDatabase.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<Guid>("BankTransactionUid");

                    b.Property<DateTimeOffset>("CreatedDateUtc");

                    b.Property<string>("Currency")
                        .IsRequired();

                    b.Property<string>("ObfuscatedCardNumber")
                        .IsRequired();

                    b.Property<int>("PaymentStatus");

                    b.Property<Guid>("Uid");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
